[package]
name = "rust-eos"
version = "0.1.0"
authors = ["maxtnt <ttg1256@naver.com>"]

[workspace]
members = [
    "eos-api",
    "eos-ecc",
    "eos",
]

[dependencies]
eos-api = { path = "eos-api" }
ecc = { path = "eos-ecc" }
eos = { path = "eos" }