[package]
name = "eos-api"
version = "0.1.0"
authors = ["maxtnt <ttg1256@naver.com>"]

[dependencies]
serde = "1.0.78"
serde_derive = "1.0.78"
serde_json = "1.0.27"
reqwest = "0.9.4"
chrono = { version = "0.4", features = ["serde"] }
config = "0.9.1"