use form::Transaction;
use serde_json::Value;

pub type account_name = String;
pub type account = String;
pub type accounts=Vec<String>;
pub type block_num_or_id = String;
pub type code = String;
pub type symbol = String;
pub type action = String;
pub type binargs=String;
pub type available_keys = Vec<String>;
pub type limit=String;
pub type timestamp =String;
pub type producer= String;
pub type confirmed = i32;
pub type previous=String;
pub type transaction_mroot=String;
pub type action_mroot=i32;
pub type version=String;
pub type new_producers = Vec<String>;
pub type header_extensions=Vec<String>;
pub type producer_signature=String;
pub type transactions=Vec<Transaction>;
pub type block_extensions=Vec<String>;
pub type signatures = Vec<String>;
pub type id =String;