[package]
name = "test_eos"
version = "0.1.0"
authors = ["maxtnuk <maxtnuk@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
eosio = "0.2"
eos={ path = "../../eos" ,version = "0.1.0"}

[profile.release]
lto = true
